services:
  - type: web
    name: lab09-galeria-peliculas
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: OMDB_API_KEY
        value: f1def80d
      - key: NEXT_PUBLIC_OMDB_API_KEY
        value: f1def80d
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff